service: kmb-eta-api
provider:
  name: aws
  stage: dev
  profile: default
  runtime: nodejs12.x
  region: ap-east-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline
  # - serverless-plugin-chrome
  
# package:
#   exclude:
#     - node_modules/puppeteer/.local-chromium/**

functions:
  eta:
    handler: handler.main
    memorySize: 2048
    timeout: 30
    layers: arn:aws:lambda:ap-east-1:578332645583:layer:lambda-chrome-layer:1
    events:
      - http:
          path: /
          method: get